name: build

on:
  push:
    branches: [ "rk3399" ]
env:
  GIT_TERMINAL_PROMPT: 0  # 禁用终端提示
  GIT_SUBMODULE_STRATEGY: recursive  # 强制递归初始化子模块
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: build RK3399-custom
      shell: 'script -q -e -c "bash {0}"'
      run: |
        scripts/enter.sh make -j12 rk3399_custom

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: |
          output/images/haos*.xz
