name: build

on:
  push:
    branches: [ "rk3399" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        scripts/enter.sh make -j12 rk3399_custom

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: |
          output/images/haos*.xz
